name: 'Godot export action'
description: 'Github action to build/export Godot 4 projects'
branding:
    icon: battery-charging
    color: purple
inputs:
    version:
        required: true
    release:
        required: false
    architecture:
        required: true
outputs:
    godot_executable:
        description: Executable path of godot
runs:
    using: 'docker'
    image: 'Dockerfile'
